### ISSUE TITLE
Ignore order when comparing equality of slices/maps

### ISSUE THREAD

**Issue by alenkacz** [go-test/deep#28]
It would be great to have option to ignore order of items in slices/maps and just assert that it contains the same element.

**Comment by daniel-nichter** [comment]
Can you give an example of what you'd like to see for both? Order shouldn't matter for maps, but it's inherent to slices.

**Comment by Bogdan-D** [comment]
I think there should be an option for slices; sometimes order is matter; sometimes doesn't. But maps are unordered by default

**Comment by tatemz** [comment]
+1 for this

I have a use case where I am testing a slice that results from go routines and the order varies

**Comment by benjamin-rood** [comment]
> Order shouldn't matter for maps, but it's inherent to slices.

It's inherent from the perspective of the data structure, but not inherent from the perspective of real use.
Sometimes people use slices as an unordered list, sometimes they use them as ordered lists.

If you are dealing with a lot of data mangling and manipulation because of the restrictiveness of Go's type system (and it will be _years_ before most libraries switch to using implementation with generics now that 1.18 has come out). A case in point is the generated go code from Protobuf definitions, which can be an absolute nightmare to deal with if you need to do any kind of validation between definitions in separate files, _especially when the underlying values of the objects being compared are absolutely identical._

**Comment by daniel-nichter** [comment]
It's been a few years, but better late than never: implemented in https://github.com/go-test/deep/pull/56 and will be released as v1.1.0 since it's a relatively major addition even though it's backwards compatible.

**Comment by benjamin-rood** [comment]
> It's been a few years, but better late than never: implemented in #56 and will be released as v1.1.0 since it's a relatively major addition even though it's backwards compatible.

Thank you, Daniel!

**Comment by daniel-nichter** [comment]
Released: https://github.com/go-test/deep/releases/tag/v1.1.0
